[[services]]
name = "appointment-scheduler-backend"
sourceDir = "backend"
builder = "dockerfile"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
startCommand = "java -jar app.jar"

[[services]]
name = "appointment-scheduler-frontend"
sourceDir = "frontend"
builder = "dockerfile"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
startCommand = "nginx -g 'daemon off;'"

[[services]]
name = "appointment-scheduler-mysql"
type = "mysql"
