version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      # Database Configuration
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-3306}
      - DB_NAME=${DB_NAME:-appointment_system}
      - DB_USERNAME=${DB_USERNAME:-your_username}
      - DB_PASSWORD=${DB_PASSWORD:-your_password}

      # Database Connection Pool Configuration
      - DB_MAX_POOL_SIZE=${DB_MAX_POOL_SIZE:-10}
      - DB_MIN_IDLE=${DB_MIN_IDLE:-5}
      - DB_CONNECTION_TIMEOUT=${DB_CONNECTION_TIMEOUT:-30000}
      - DB_IDLE_TIMEOUT=${DB_IDLE_TIMEOUT:-600000}
      - DB_MAX_LIFETIME=${DB_MAX_LIFETIME:-1800000}

      # JWT Configuration
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_key_here_make_it_long_and_random}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-86400000}
      - JWT_HEADER=${JWT_HEADER:-Authorization}
      - JWT_PREFIX=${JWT_PREFIX:-Bearer }

      # Appointment Configuration
      - APPOINTMENT_CANCELLATION_LIMIT_HOURS=${APPOINTMENT_CANCELLATION_LIMIT_HOURS:-24}
      - APPOINTMENT_GRACE_PERIOD_MINUTES=${APPOINTMENT_GRACE_PERIOD_MINUTES:-15}
      - APPOINTMENT_ALLOW_PAST_CANCELLATIONS=${APPOINTMENT_ALLOW_PAST_CANCELLATIONS:-false}
      - APPOINTMENT_DEFAULT_SLOT_MINUTES=${APPOINTMENT_DEFAULT_SLOT_MINUTES:-30}
      - APPOINTMENT_DEFAULT_PROVIDER_NUMERIC_ID=${APPOINTMENT_DEFAULT_PROVIDER_NUMERIC_ID:-1}

      # Server Configuration
      - SERVER_PORT=${SERVER_PORT:-8080}

      # Logging Configuration
      - LOGGING_LEVEL_SPRING=${LOGGING_LEVEL_SPRING:-INFO}
      - LOGGING_LEVEL_APP=${LOGGING_LEVEL_APP:-INFO}
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-your_password}
      - MYSQL_DATABASE=${DB_NAME:-appointment_system}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
